FROM microsoft/aspnetcore:1.1.2
#FROM ostusa/aspnetcore:1.1.1
WORKDIR /app
COPY ./publish .
COPY ./src/SimplCommerce.WebHost/appsettings.json .
ENV ASPNETCORE_URLS http://*:9000
ENV ConnectionStrings__DefaultConnection Data Source=mssql;Initial Catalog=SimplCommerce;Integrated Security=False;User Id=sa;Password=aklsdjAf5%ienl8347D%(wef;MultipleActiveResultSets=True
ENTRYPOINT ["dotnet", "SimplCommerce.WebHost.dll"]