apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: mssql-backup
  namespace: simplcommerce
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 30
      template:
        spec:
          containers:
          - name: mssql-server
            image: ba2017/simplcommerce:mssql-backup
            env:
              - name: SA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: simplcommerce-db-credentials
                    key: sa_password
          restartPolicy: Never